Repository SyedImtiyaz-1/GetTechProjects, pull requests merged in 2023-10, with the labels that each got.

#43 [Fixed]: Updated careers.html
  careers.html
Labels: process1Oct

#46 Footer design
  CONTRIBUTING.md
  index.html
  main.css
Labels: process1Oct

#62 project: Added Tesla clone project
  CONTRIBUTING.md
  backend/public/img/tesla-clone-1.png
  backend/public/img/tesla-clone-2.png
  backend/public/img/tesla-clone.png
  backend/public/projects.json
Labels: hacktoberfest, project+

#66 "ourTeam" page attached from the backend
  .DS_Store
  backend/.DS_Store
  backend/public/.DS_Store
  backend/public/img/.DS_Store
  backend/public/img/CMS.jpeg
  backend/public/img/PM.jpeg
  backend/public/img/analytic.jpeg
  backend/public/img/quality.jpeg
  backend/public/ourTeam/index.html
  backend/public/ourTeam/ourTeam.css
  backend/public/ourTeam/ourTeam.js
  backend/server.js
  images/.DS_Store
  index.html
Labels: hacktoberfest

#55 Issue#53 resloved
  chatBot/style.css
Labels: hacktoberfest

#78 Bug Fixed
  CONTRIBUTING.md
  backend/public/img/tesla-1.png
  backend/public/img/tesla-2.png
  backend/public/img/tesla-clone.png
  backend/public/projects.json
Labels: hacktoberfest

#77 [ui-upgrade]: UI Enhancement in the form section #72
  main.css
Labels: hacktoberfest

#45 [FIXED]: Updated Link for Logo
  backend/public/index.html
  careers.html
Labels: process1Oct

#47 Fixes navbar and login/Logout btn.
  careers.html
  css/careers.css
  index.html
  js/careers.js
  main.css
  main.js
Labels: hacktoberfest

#86 Format Text of Description and Mail id to Normal #82
  main.css
Labels: hacktoberfest

#93 Enhancing UI Layout and Responsiveness of Form Section
  CONTRIBUTING.md
  main.css
Labels: hacktoberfest

#91 Replaced Footer UI on Careers Page
  careers.html
  css/careers.css
  js/carrers.js
Labels: hacktoberfest

#96 enahnce(Issue#79):home-latest-project-cards
  CONTRIBUTING.md
  backend/public/style.css
  index.html
  main.css
Labels: hacktoberfest

#90 Fix text format
  index.html
  main.css
Labels: hacktoberfest, UI

#101 feat-live-counting #issue99
  index.html
  main.js
Labels: hacktoberfest

#110 Update login button text to 'Log In'
  index.html
Labels: hacktoberfest

#117 Fix footer team button
  CONTRIBUTING.md
  index.html
Labels: hacktoberfest

#137 The pop-Up feature is Added when, user hover over any product. [ui-upgrade]: . #33
  CONTRIBUTING.md
  backend/public/style.css
  index.html
  main.css
Labels: hacktoberfest, UI

#128 #122 - Page stuck bug
  CONTRIBUTING.md
  backend/public/projects.js
Labels: hacktoberfest

#146 added few changes in css to make a balanced design
  index.html
  main.css
Labels: hacktoberfest

#167 changes
  careers.html
  index.html
Labels: hacktoberfest

#220 Form validations
  index.html
  js/contact.js
Labels: hacktoberfest

#217 Solved #207
  backend/public/ourTeam/chatBot/style.css
  backend/public/ourTeam/index.html
  backend/public/ourTeam/ourTeam.css
  backend/public/ourTeam/style.css
  chatBot/style.css
  main.css
Labels: hacktoberfest, waiting

#232 Apple Vision Pro Clone
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00001.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00002.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00003.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00004.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00005.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00006.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00007.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00008.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00009.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00010.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00011.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00012.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00013.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00014.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00015.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00016.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00017.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00018.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00019.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00020.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00021.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00022.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00023.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00024.png
  Projects/Apple-Vision-Pro_Clone/Apple vision canvas images/Vision00025.png
  Projects/Apple-Vision-Pro_Clone/Apple vision image.png
  Projects/Apple-Vision-Pro_Clone/index.html
  Projects/Apple-Vision-Pro_Clone/script.js
  Projects/Apple-Vision-Pro_Clone/style.css
Labels: hacktoberfest, project+

#246 dark mode added
  CONTRIBUTING.md
  index.html
  js/theme.js
  main.css
  main.js
Labels: hacktoberfest, hacktoberfest-accepted

#242 Our team page modded
  backend/public/ourTeam/index.html
  backend/public/ourTeam/ourTeam.css
  backend/public/ourTeam/ourTeam.js
Labels: hacktoberfest-accepted

#248 Revert "Our team page modded"
  backend/public/ourTeam/index.html
  backend/public/ourTeam/ourTeam.css
  backend/public/ourTeam/ourTeam.js
Labels: hacktoberfest-accepted
