Repository SyedImtiyaz-1/GetTechProjects, pull requests merged in 2024-05, with the labels that each got.

#308 Weight converter application added
  CONTRIBUTING.md
  backend/public/img/WeightConverterlogo.png
  backend/public/img/ss1.png
  backend/public/img/ss2.png
  backend/public/projects.json
Labels: level-2, gssoc

#339 Added Currency Converter App
  backend/public/img/currencyConverter.png
  backend/public/img/currencylogo.png
  backend/public/projects.json
Labels: level-3, gssoc, gssoc24

#345 Added Spotify Clone App
  backend/public/img/spotifyLogo.jpg
  backend/public/img/spotifyclone.jpg
  backend/public/projects.json
  backend/public/style.css
Labels: level-3, gssoc, gssoc24

#364 Added animated counter
  index.html
  main.js
  package-lock.json
  package.json
Labels: level2, gssoc, gssoc24

#393 Added To-do-List App
  backend/public/img/colorconvertLogo.jpg
  backend/public/img/microsoftLogo.jpg
  backend/public/img/microsoftlogo.png
  backend/public/img/passcheckLogo.avif
  backend/public/img/todolist1.jpg
  backend/public/img/todolist2.png
  backend/public/img/todolistLogo.png
  backend/public/projects.json
Labels: level3, gssoc

#468 added ball game
  backend/public/img/mindballGame.png
  backend/public/projects.json
Labels: level3, gssoc

#447 online stationery shop addded
  backend/public/img/Stationery_Shop.jpeg
  backend/public/img/Stationery_Shop.jpg
  backend/public/img/Stionery_Shop2.jpeg
  backend/public/img/Stionery_Shop3.jpeg
  backend/public/projects.json
Labels: level2, gssoc

#493 Added Password Generator
  backend/public/img/passwordgen.png
  backend/public/img/passwordgenLogo.jpeg
  backend/public/projects.json
Labels: level3, gssoc
