Repository SyedImtiyaz-1/GetTechProjects, pull requests merged in 2024-06, with the labels that each got.

#545 Adding Weather App
  CONTRIBUTING.md
  backend/public/img/weather.png
  backend/public/img/weatherLogo.png
  backend/public/projects.json
Labels: level3, gssoc

#564 Added Landing Page Site
  backend/public/img/landingLogo.jpg
  backend/public/img/landingPage.png
  backend/public/projects.json
Labels: level3, gssoc

#583 Added Analog Clock Project
  backend/public/img/analogClockLogo.jpg
  backend/public/img/analogclock.png
  backend/public/projects.json
Labels: level3, gssoc

#611 Adding QR code generator
  backend/public/img/qrcode1.png
  backend/public/img/qrcode2.png
  backend/public/img/qrcodeLogo.png
  backend/public/index.html
  backend/public/projects.js
  backend/public/projects.json
  careers.html
Labels: level3, gssoc

#563 Solved issue #485- Quantum Maze
  backend/public/img/Quantum_Maze.png
  backend/public/img/Quantum_Maze1.png
  backend/public/projects.json
Labels: level2, gssoc

#538 Tourism Website Created
  CONTRIBUTING.md
  Projects/Tourism/css/responsive.css
  Projects/Tourism/css/style.css
  Projects/Tourism/img/GitHub120px.png
  Projects/Tourism/img/android-chrome-192x192.png
  Projects/Tourism/img/android-chrome-512x512.png
  Projects/Tourism/img/apple-touch-icon.png
  Projects/Tourism/img/bg.png
  Projects/Tourism/img/bg2.png
  Projects/Tourism/img/carousel-img1.jpg
  Projects/Tourism/img/carousel-img2.jpg
  Projects/Tourism/img/carousel-img3.jpg
  Projects/Tourism/img/carousel-img4.jpg
  Projects/Tourism/img/carousel-img5.jpg
  Projects/Tourism/img/carousel-img6.jpg
  Projects/Tourism/img/favicon-16x16.png
  Projects/Tourism/img/favicon-32x32.png
  Projects/Tourism/img/favicon.ico
  Projects/Tourism/img/header-bg.jfif
  Projects/Tourism/img/img1.jfif
  Projects/Tourism/img/img2.jfif
  Projects/Tourism/img/img3.png
  Projects/Tourism/img/img4.png
  Projects/Tourism/img/img5.png
  Projects/Tourism/img/img6.png
  Projects/Tourism/img/menu-btn.png
  Projects/Tourism/img/mountain.png
  Projects/Tourism/img/mountain_dark.jpg
  Projects/Tourism/img/site.webmanifest
  Projects/Tourism/index.html
  Projects/Tourism/js/script.js
  backend/public/img/tourism.png
  backend/public/img/tourism1.png
  backend/public/img/tourism_logo.png
  backend/public/projects.json
Labels: level2, gssoc

#684 Added Myntra Shopping App
  Projects/Myntra Clone/home.png
  Projects/Myntra Clone/index.html
  Projects/Myntra Clone/style.css
  Projects/Myntra Clone/utils.css
  backend/public/img/Myntra.png
  backend/public/img/myntralogo.webp
  backend/public/projects.json
Labels: level2, gssoc

#443 chore: project addition by Nisarga - Real Estate App #406
  CONTRIBUTING.md
  Projects/MERN-EstateSquare/api/controllers/auth.controller.js
  Projects/MERN-EstateSquare/api/controllers/listing.controller.js
  Projects/MERN-EstateSquare/api/controllers/user.controller.js
  Projects/MERN-EstateSquare/api/index.js
  Projects/MERN-EstateSquare/api/models/listing.model.js
  Projects/MERN-EstateSquare/api/models/user.model.js
  Projects/MERN-EstateSquare/api/routes/auth.route.js
  Projects/MERN-EstateSquare/api/routes/listing.route.js
  Projects/MERN-EstateSquare/api/routes/user.route.js
  Projects/MERN-EstateSquare/api/utils/error.js
  Projects/MERN-EstateSquare/api/utils/verifyUser.js
  Projects/MERN-EstateSquare/client/.eslintrc.cjs
  Projects/MERN-EstateSquare/client/index.html
  Projects/MERN-EstateSquare/client/package-lock.json
  Projects/MERN-EstateSquare/client/package.json
  Projects/MERN-EstateSquare/client/postcss.config.js
  Projects/MERN-EstateSquare/client/src/App.jsx
  Projects/MERN-EstateSquare/client/src/components/Contact.jsx
  Projects/MERN-EstateSquare/client/src/components/Header.jsx
  Projects/MERN-EstateSquare/client/src/components/ListingItem.jsx
  Projects/MERN-EstateSquare/client/src/components/OAuth.jsx
  Projects/MERN-EstateSquare/client/src/components/PrivateRoute.jsx
  Projects/MERN-EstateSquare/client/src/firebase.js
  Projects/MERN-EstateSquare/client/src/index.css
  Projects/MERN-EstateSquare/client/src/main.jsx
  Projects/MERN-EstateSquare/client/src/pages/About.jsx
  Projects/MERN-EstateSquare/client/src/pages/CreateListing.jsx
  Projects/MERN-EstateSquare/client/src/pages/Home.jsx
  Projects/MERN-EstateSquare/client/src/pages/Listing.jsx
  Projects/MERN-EstateSquare/client/src/pages/Profile.jsx
  Projects/MERN-EstateSquare/client/src/pages/Search.jsx
  Projects/MERN-EstateSquare/client/src/pages/SignIn.jsx
  Projects/MERN-EstateSquare/client/src/pages/SignUp.jsx
  Projects/MERN-EstateSquare/client/src/pages/UpdateListing.jsx
  Projects/MERN-EstateSquare/client/src/redux/store.js
  Projects/MERN-EstateSquare/client/src/redux/user/userSlice.js
  Projects/MERN-EstateSquare/client/tailwind.config.js
  Projects/MERN-EstateSquare/client/vite.config.js
  backend/public/img/Real-estate_3.png
  backend/public/img/Real.png
  backend/public/img/estate.png
  backend/public/projects.json
Labels: gssoc, level1

#728 Email Subscription form with google sheet
  Projects/EmailSubscriptionwithGoogleSheet/assests/bg.jpg
  Projects/EmailSubscriptionwithGoogleSheet/index.html
  Projects/EmailSubscriptionwithGoogleSheet/script.js
  Projects/EmailSubscriptionwithGoogleSheet/style.css
  backend/public/img/Email-Subscription-with-google-sheet.png
  backend/public/projects.json
Labels: level2, gssoc
